# Generated by Django 5.2.1 on 2025-06-09 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('comprobante_entrada', models.FileField(blank=True, null=True, upload_to='comprobantes_empleado/')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Turno de empleado',
                'verbose_name_plural': 'Turnos de empleados',
                'ordering': ['-entrada'],
            },
        ),
    ]
