# Generated by Django 5.2.1 on 2025-06-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(default=0, help_text='Porcentaje de descuento aplicado al producto', verbose_name='Descuento (%)'),
        ),
    ]
